services:
  mote-frontend:
    container_name: mote-frontend
    image: felipe98mz/mote-frontend:1.0.2
    env_file:
      - ./prod.env
    networks:
      - mote-network
    ports:
      - "80:80"
    volumes:
      - ./scripts/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mote-backend
  mote-backend:
    container_name: mote-backend
    image: felipe98mz/mote-backend:1.0.2
    env_file:
      - ./prod.env
    networks:
      - mote-network
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - ./prod.env
    volumes:
      - mongo-data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - mote-network
volumes:
  mongo-data:
    driver: local

networks:
  mote-network:
    driver: bridge

